[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agenda"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
agenda = "cli:main"

